apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: petstore-worker
    behavior: merge
    literals:
      - APP_TEMPORAL_DEFAULT_WORKER_VERSIONING_BEHAVIOR=AUTO_UPGRADE
