resources:
  - connection.yml
  - route.yml
  - service.yml
  - workerdeployment.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: petstore-worker
    envs:
      - config.env