spring:
  application:
    name: petstore
  threads:
    virtual:
      enabled: true
  temporal:
    start-workers: true
    namespace: ${app.temporal.namespace}
    connection:
      target: ${app.temporal.target}
      apiKey: ${app.temporal.apiKey:}
    workflow-cache:
      using-virtual-workflow-threads: true
    workersAutoDiscovery:
      packages:
      - me.nzuguem.petstore.inventory
      - me.nzuguem.petstore.order
      - me.nzuguem.petstore.notification
      - me.nzuguem.petstore.payment
      - me.nzuguem.petstore.workflow
      - me.nzuguem.petstore.shipment
    workers:
    - task-queue: ${app.temporal.task-queues.purchase-order}
      name: ${app.temporal.task-queues.purchase-order}-worker
      virtual-thread:
        using-virtual-threads: true
      deployment-properties:
        use-versioning: ${app.temporal.use-worker-versioning}
        deployment-name: ${TEMPORAL_DEPLOYMENT_NAME:${spring.application.name}}
        build-id: ${TEMPORAL_WORKER_BUILD_ID:404}
        default-versioning-behavior: ${app.temporal.default-worker-versioning-behavior}
    - task-queue: ${app.temporal.task-queues.order}
      name: ${app.temporal.task-queues.order}-worker
      virtual-thread:
        using-virtual-threads: true
      deployment-properties:
        use-versioning: ${app.temporal.use-worker-versioning}
        deployment-name: ${TEMPORAL_DEPLOYMENT_NAME:${spring.application.name}}
        build-id: ${TEMPORAL_WORKER_BUILD_ID:404}
        default-versioning-behavior: ${app.temporal.default-worker-versioning-behavior}
    - task-queue: ${app.temporal.task-queues.notification}
      name: ${app.temporal.task-queues.notification}-worker
      virtual-thread:
        using-virtual-threads: true
      deployment-properties:
        use-versioning: ${app.temporal.use-worker-versioning}
        deployment-name: ${TEMPORAL_DEPLOYMENT_NAME:${spring.application.name}}
        build-id: ${TEMPORAL_WORKER_BUILD_ID:404}
        default-versioning-behavior: ${app.temporal.default-worker-versioning-behavior}
    - task-queue: ${app.temporal.task-queues.inventory}
      name: ${app.temporal.task-queues.inventory}-worker
      virtual-thread:
        using-virtual-threads: true
      deployment-properties:
        use-versioning: ${app.temporal.use-worker-versioning}
        deployment-name: ${TEMPORAL_DEPLOYMENT_NAME:${spring.application.name}}
        build-id: ${TEMPORAL_WORKER_BUILD_ID:404}
        default-versioning-behavior: ${app.temporal.default-worker-versioning-behavior}
    - task-queue: ${app.temporal.task-queues.payment}
      name: ${app.temporal.task-queues.payment}-worker
      virtual-thread:
        using-virtual-threads: true
      deployment-properties:
        use-versioning: ${app.temporal.use-worker-versioning}
        deployment-name: ${TEMPORAL_DEPLOYMENT_NAME:${spring.application.name}}
        build-id: ${TEMPORAL_WORKER_BUILD_ID:404}
        default-versioning-behavior: ${app.temporal.default-worker-versioning-behavior}
    - task-queue: ${app.temporal.task-queues.shipment}
      name: ${app.temporal.task-queues.shipment}-worker
      virtual-thread:
        using-virtual-threads: true
      deployment-properties:
        use-versioning: ${app.temporal.use-worker-versioning}
        deployment-name: ${TEMPORAL_DEPLOYMENT_NAME:${spring.application.name}}
        build-id: ${TEMPORAL_WORKER_BUILD_ID:404}
        default-versioning-behavior: ${app.temporal.default-worker-versioning-behavior}

## OpenTelemetry
### https://github.com/spring-projects/spring-boot/issues/41460#issuecomment-2399968462
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: 1.0
    export:
      otlp:
        enabled: true
  otlp:
    metrics:
      export:
        enabled: true
        url: ${app.observability.otel-base-url}/v1/metrics
  logging:
    export:
      otlp:
        enabled: false
  opentelemetry:
    enabled: true
    logging:
      export:
        otlp:
          endpoint: ${app.observability.otel-base-url}/v1/logs
          transport: http
    tracing:
      export:
        otlp:
          endpoint: ${app.observability.otel-base-url}/v1/traces
          transport: http

app:
  symmetric-codec:
    key: ${codec_key:Bp%qO*uf69ULbcfM}
  observability:
    otel-base-url: http://localhost:4318
  deploy:
    version: "provided-by-ci"
  temporal:
    namespace: ${TEMPORAL_NAMESPACE:default} # TEMPORAL_NAMESPACE come from K8s Temporal Worker Controller
    target: ${TEMPORAL_ADDRESS:127.0.0.1:7233} # TEMPORAL_ADDRESS come from K8s Temporal Worker Controller
    use-worker-versioning: false
    default-worker-versioning-behavior: UNSPECIFIED
    task-queues:
      purchase-order: purchase-order-tasks
      order: order-tasks
      notification: notification-tasks
      inventory: inventory-tasks
      payment: payment-tasks
      shipment: shipment-tasks
    nexus-endpoints:
      prefix: ""
      payment: ${app.temporal.nexus-endpoints.prefix}payment
