spring:
  application:
    name: petstore
  temporal:
    start-workers: true
    namespace: ${app.temporal.namespace}
    connection:
      target: ${app.temporal.target}
      apiKey: ${app.temporal.apiKey}
    workflow-cache:
      using-virtual-workflow-threads: true
    workersAutoDiscovery:
      packages:
      - me.nzuguem.petstore.inventory
      - me.nzuguem.petstore.order
      - me.nzuguem.petstore.notification
      - me.nzuguem.petstore.payment
      - me.nzuguem.petstore.workflow
      - me.nzuguem.petstore.shipment
    workers:
    - task-queue: ${app.temporal.task-queues.purchase-order}
      name: ${app.temporal.task-queues.purchase-order}-worker
      virtual-thread:
        using-virtual-threads: true
    - task-queue: ${app.temporal.task-queues.order}
      name: ${app.temporal.task-queues.order}-worker
      virtual-thread:
        using-virtual-threads: true
    - task-queue: ${app.temporal.task-queues.notification}
      name: ${app.temporal.task-queues.notification}-worker
      virtual-thread:
        using-virtual-threads: true
    - task-queue: ${app.temporal.task-queues.inventory}
      name: ${app.temporal.task-queues.inventory}-worker
      virtual-thread:
        using-virtual-threads: true
    - task-queue: ${app.temporal.task-queues.payment}
      name: ${app.temporal.task-queues.payment}-worker
      virtual-thread:
        using-virtual-threads: true
    - task-queue: ${app.temporal.task-queues.shipment}
      name: ${app.temporal.task-queues.shipment}-worker
      virtual-thread:
        using-virtual-threads: true

## OpenTelemetry
### https://github.com/spring-projects/spring-boot/issues/41460#issuecomment-2399968462
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  opentelemetry:
    resource-attributes:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4317/v1/traces
      export:
        enabled: true
      transport: grpc
    logging:
      export:
        enabled: false
      transport: grpc
      endpoint: http://localhost:4317/v1/logs

app:
  symmetric-codec:
    key: ${codec_key:Bp%qO*uf69ULbcfM}
  temporal:
    namespace: default
    target: 127.0.0.1:7233
    task-queues:
      prefix: ""
      purchase-order: ${app.temporal.task-queues.prefix}purchase-order-tasks
      order: ${app.temporal.task-queues.prefix}order-tasks
      notification: ${app.temporal.task-queues.prefix}notification-tasks
      inventory: ${app.temporal.task-queues.prefix}inventory-tasks
      payment: ${app.temporal.task-queues.prefix}payment-tasks
      shipment: ${app.temporal.task-queues.prefix}shipment-tasks
    nexus-endpoints:
      prefix: ""
      payment: ${app.temporal.nexus-endpoints.prefix}payment
