services:
  lgtm:
    image: grafana/otel-lgtm:0.7.8
    container_name: lgtm
    ports:
      - "3000:3000" # Grafana
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver