resources:
  - namespace.yml
  - connection.yml
  - route.yml
  - service.yml
  - workerdeployment.yml

configMapGenerator:
  - name: petstore-worker
    envs:
      - config.env

configurations:
  - nameReference.yml
